services:
  frontend-manage:
    build:
      context: ./../cms-front-vue
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
  frontend-web:
    build:
      context: ./../cms-web-vue
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: cms
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  mysql-data:
