services:
  frontend-manage:
    build:
      context: ./../cms-front-vue
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
  frontend-web:
    build:
      context: ./../cms-web-vue
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: cms
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-manage
      - frontend-web
      - backend
volumes:
  mysql-data:
